// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Persistence;

#nullable disable

namespace UrlShortener.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250707200840_Add_CreatedOn")]
    partial class Add_CreatedOn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Persistence.Entities.Url", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("long_url");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("short_url");

                    b.HasKey("Id")
                        .HasName("pk_urls");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_urls_code");

                    b.ToTable("urls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
