// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.Persistence;

#nullable disable

namespace UrlShortener.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Persistence.Entities.Url", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<int>("Counter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("counter");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("long_url");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("short_url");

                    b.HasKey("Id")
                        .HasName("pk_urls");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_urls_code");

                    b.HasIndex("ShortUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_urls_short_url");

                    b.ToTable("urls", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
